[package]
name = "firdecim2"
version = "0.1.0"
edition = "2024"

[dependencies]
num="0.4.3"
crossbeam="0.8.4"
lockfree-object-pool = "0.1.6"
rayon="1.11.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
